### ISSUE TITLE
Error occured while trying to install adminer service | Step 6/10 : RUN docker-php-ext-install

### ISSUE THREAD

**Issue by vinit0108** [mafudge/learn-databases#2]
Description:
I am using Ubuntu 18.04, got an error when trying to install adminer service, Pasting the error below

-------------------------------
Step 6/10 : RUN docker-php-ext-install            pdo_odbc pdo_dblib
 ---> Running in 2f814129ae61
/bin/sh /usr/src/php/ext/pdo_odbc/libtool --mode=compile cc -I/usr/local/include/php/ext  -I/usr/include -DPDO_ODBC_TYPE=\"unixODBC\" -I. -I/usr/src/php/ext/pdo_odbc -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_odbc/include -I/usr/src/php/ext/pdo_odbc/main -I/usr/src/php/ext/pdo_odbc -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/pdo_odbc/pdo_odbc.c -o pdo_odbc.lo 
make: /bin/sh: Operation not permitted
make: *** [Makefile:192: pdo_odbc.lo] Error 127
The command '/bin/sh -c docker-php-ext-install            pdo_odbc pdo_dblib' returned a non-zero code: 2
ERROR: Service 'adminer' failed to build : Build failed
 @----------------------------------
@mafudge @mafudge-su

**Comment by mafudge** [comment]
What CPU architecture?

**Comment by vinit0108** [comment]
@mafudge 64-bit

**Comment by mafudge** [comment]
x86? ARM?

**Comment by mafudge** [comment]
Try adding this to the docker-compose.yml in the adminer section:
```
adminer:
   platform: linux/amd64

```
Or just pull the latest from this repository

**Comment by vinit0108** [comment]
> x86? ARM?

![Screenshot from 2021-08-31 09-39-25](https://user-images.githubusercontent.com/20949380/131512887-1c8e19e1-11c5-42f2-8df5-fd0e19ec0f0c.png)

**Comment by vinit0108** [comment]
> Try adding this to the docker-compose.yml in the adminer section:
> 
> ```
> adminer:
>    platform: linux/amd64
> ```
> 
> Or just pull the latest from this repository

Will do.
